### ISSUE TITLE
Centos 7 Segmentation fault

### ISSUE THREAD

**Issue by nickdodd25** [oscar-broman/SKY#19]
When running the newest version on centos 7 i get a segmentation fault. I ran the server using gbd and the log is here.... https://pastebin.com/t5RazKz3

It appears to be a issue with subhooks. I tried updating subhooks to the latest version but i am unable to compile sky. I receive this error.....https://pastebin.com/18DvqWQ3

Stuff like this is still beond my abilitys to fix. Any suggestions on a fix? Or if you could possibly fix this. Or if anyone else knows of a fix.

Or is this an OS issue?

**Comment by VariableTM** [comment]
I get this issue on Debian, been unable to compile it recently. It was compiling fine few months ago.

**Comment by VariableTM** [comment]
However, I have a SKY.so version which I compiled last year (Sep, 2018) on a Debian 8 64-bits machine. If you would like to temporary use it as a fix. It was working flawlessly.

**Comment by nickdodd25** [comment]
This has been solved. I chatted with slice on discord and he helped me out with the fixes. I also created a pull request.
