### ISSUE TITLE
Keys don't work in the latest release

### ISSUE THREAD

**Issue by ahmedh2o1999** [oscar-broman/SKY#27]
I compiled SKY on my Debian 8 amd64 VPS. Keys don't work (tried KEY_YES, KEY_NO and KEY_CTRL_BACK). Like, the keys can't be scripted. OnPlayerKeyStateChange has no effect.

https://h2omultiplayer.com/server/SKY.so

This is the compiled binary.

**Comment by leonedeandre** [comment]
Had the same issue. There's a open pull request here https://github.com/oscar-broman/SKY/pull/26/commits fixing that issue i believe

**Comment by ahmedh2o1999** [comment]
Indeed, it works fine now.
