### ISSUE TITLE
Merge 0.3DL into master

### ISSUE THREAD

**Issue by ADRFranklin** [oscar-broman/SKY#29]
The 0.3DL branch should be merged into master at some point to keep things together.

**Comment by Whitetigerswt** [comment]
It's based off newer versions of the YSF plugin. It might be better to redo some of it.

**Comment by ADRFranklin** [comment]
I agree, we should definitely start looking at replacing the old YSF code with newer parts.

A lot of the code that exists in both 0,3.7 and 0.3DL versions have hooks for functions that are not even used in the plugin. They should be removed.

**Comment by ADRFranklin** [comment]
@Whitetigerswt Could you tell me where you at with the 0.3DL version? Like what was the issue you had when trying to merge the two before?

**Comment by Whitetigerswt** [comment]
Well, the code in 0.3DL came from YSF, which had many rewritten hooks instead of just using memory addresses. It's not immediately clear by looking at the code how to merge

**Comment by ADRFranklin** [comment]
@Whitetigerswt I've re-done the building process for 0.3.DL and docker, it now compiles fine for Linux/Windows using docker, I have also provided a [taskfile](https://taskfile.dev) to make it easier to build for both.

Could you try these out for me and confirm that everything is working for you too? I have not tried building with Visual Studios (I don't like it, personally).

**Comment by ADRFranklin** [comment]
@Whitetigerswt Actually you might need to wait for https://github.com/maddinat0r/samp-plugin-sdk
to merge my PR

Since I've moved to using submodules more.

**Comment by ADRFranklin** [comment]
Okay, you can ignore the last message, Maddinat0r merged it.

**Comment by Whitetigerswt** [comment]
I don't have an easy way to test it. I don't own a server or have SA-MP installed. Most likely, if it doesn't crash 0.3DL server when loaded then it's good since it does most of the hooking at that point.

Last time, I just made sure it didn't crash the server and posted on the forum asking others to try it: https://forum.sa-mp.com/showpost.php?p=4001276&postcount=137

I can compile on Windows/Visual Studio though if needed

**Comment by ADRFranklin** [comment]
I've tested 0.3.DL on each of my servers, all different gamemodes. However I don't own or run any 0.3.DL servers, so I am going to have to find someone who can try it out.

It does work on 0.3.7 servers currently.

**Comment by ADRFranklin** [comment]
I think Instead of merging with master, I might just replace master with 0.3DL after we confirm it works on both versions of sa-mp. I've updated 0.3.DL version with any changes that where made to master, so it is up to date.

**Comment by Whitetigerswt** [comment]
I did some updates to visual studio config and setup appveyor to Auto-compile on windows after every commit. I sent a Windows build to Crayder and asked him to post here with what he finds testing.

**Comment by ADRFranklin** [comment]
Ah, perfect. Should we add travis for Linux builds too? I actually tried before to add both, but wasn't able too, because I am not the owner of the repo.

(atleast that is what the sites told me)
If you know how to get around that, could you try setting up travis?

**Comment by Crayder** [comment]
0.3.DL version breaks position and health value sync. The bar doesn't track damage and I don't seem to die (only tested fall damage from a building). Position and facing angle always returns the same, the class position and 0 for the angle.

**Comment by ADRFranklin** [comment]
@Crayder I have fixed the sync issue and I have cleaned up SKY so that all the non-used stuff is gone, I have also used a `hacky` solution from Illidan to load the correct 0.3DL structs at runtime.

Could you test this and make sure it works for you? 
[SKY.zip](https://github.com/oscar-broman/SKY/files/3471224/SKY.zip)

**Comment by ADRFranklin** [comment]
@Whitetigerswt Crayder says everything is working now, so do you want to take a look over the code and make sure you are happy with everything before we decide to merge later?

**Comment by Whitetigerswt** [comment]
If it's working feel free to merge

**Comment by ADRFranklin** [comment]
@Whitetigerswt @Crayder Has been merged and a new release has been made

**Comment by Crayder** [comment]
Sweet 👍 

I'll reupload the colored bars pull request soon, seems completely functional.
