### ISSUE TITLE
TextDrawSetStringForPlayer conflicts with YSF

### ISSUE THREAD

**Issue by NexiusTailer** [oscar-broman/SKY#30]
TextDrawSetStringForPlayer function conflicts with the same native in YSF

**Comment by ADRFranklin** [comment]
I have also noticed this, I am currently working on merging 0.3DL so I will remember to change the natives to work with YSF

**Comment by ADRFranklin** [comment]
I'm debating whether this function should be removed from SKY, since it doesn't have anything to do with the original intentions of SKY. YSF offers this anyway and is probably better suited for it.

Thoughts?

**Comment by NexiusTailer** [comment]
So there are two ways: rename it for compatibility reasons so people who have used it will continue use it. Or just remove it, so they can use the same function but from YSF. I'm not going to recommend to delete it "just because I didn't use this function before", but I would probably remove it if I were you...

**Comment by ADRFranklin** [comment]
I'll rename it, and add some backwards compatibility if YSF is not used. Then I will mark it as deprecated, so people are aware, then I will remove it later on.

**Comment by ADRFranklin** [comment]
This has been fixed in the latest version of the 0.3DL branch, once it's merged you will see the fix.
