### ISSUE TITLE
FreezeSyncData and SendLastSyncData works only with onfoot sync

### ISSUE THREAD

**Issue by NexiusTailer** [oscar-broman/SKY#31]
I think it would be nice if these functions could work with all types of player sync and not only with the onfoot type. I understand that these functions (like all other functions in this plugin too) was presented firstly for weapon-config and there can be no need in this abilities for wc, but it can be useful for any other scripts which may use it for different systems.

**Comment by ADRFranklin** [comment]
I will take this in to consideration at a later point.

**Comment by ADRFranklin** [comment]
Could you give me a couple of example of data you want to be able to re-send / freeze?

**Comment by NexiusTailer** [comment]
Actually I'm going to use this feature to make more advanced anti-unfreeze system which wouldn't just decync the player (as others will see "sandglass" above his head), I want to resend the last player's data instead, so this player will be freezed literally not being able to ignore it.

So, there are several ways how you can make this function work for all types of synchronizations:
1) Add a new argument of the type of synchronization that is needed to freeze, for example, we will pass the onfoot sync to it (and thus, if the player switches his sync, for example to incar sync, the function will continue to work only on that type of sync which we indicated for freezing, i.e. onfoot sync)
2) The arguments of the function will remain the same, but this function will now decide for itself what type of sync it is necessary to freeze (depending on the type that the player is sending at the moment) and when the player changes sync type, the function will continue to freeze the new type accordingly.

**Comment by ADRFranklin** [comment]
I will see what I can for the next release. The code needs some work and further improvements to protect it against collisions with YSF and other plugins.

**Comment by ADRFranklin** [comment]
I will be planning this change next, now that all the 0.3DL stuff has finally been cleaned up.

**Comment by NexiusTailer** [comment]
Could I somehow help with the test of any drafts or in another way?

**Comment by ADRFranklin** [comment]
Ah, Sorry this got pushed aside while I was fixing a bug, was took priority. I will get back to this over the next few days.

I will most likely be implementing new natives for this, and deprecate the old ones

**Comment by ADRFranklin** [comment]
@NexiusTailer You going to be free tomorrow to test this? I've almost finished with it. I've also fixed a few issues I found where Additional Keys where not being sent when `SendLastSyncData` was used. The new native is called `SendLastSyncPacket` and does contain a type of packet to use.

Hopefully this will be more useful now.

**Comment by NexiusTailer** [comment]
Think yes, I'll try to go test as you request it. Thank you

**Comment by ADRFranklin** [comment]
[release-linux.tar.gz](https://github.com/oscar-broman/SKY/files/3993186/release-linux.tar.gz)
[release-windows.zip](https://github.com/oscar-broman/SKY/files/3993187/release-windows.zip)

@NexiusTailer 
Here you go, hope this works first time, wouldn't that be nice :D

**Comment by ADRFranklin** [comment]
@NexiusTailer have you had time to test it?

**Comment by NexiusTailer** [comment]
Yeah, I just started testing it. Currently I have one little suggestion to make the function work also for spectating data as it is also the part of original OnPlayerUpdate.

Anyway I'll continue to test it, thanks for nice update :)

P.s. At the time I have an ability to test it only on windows server, so I didn't test the linux version yet...

**Comment by ADRFranklin** [comment]
I'm not sure as to what you are expecting for Spectating, as that's an RPC and not really part of the packet hooks that we are currently using to store and send previous sync data.

I'm glad you are happy with the update, and it should work on Linux if it works on Windows.

**Comment by NexiusTailer** [comment]
Spectating sync ins't documented on both BrunoBM16's and Pawn.Raknet's wikis but it declared in Pawn.Raknet include file as
```
        enum PR_SpectatingSync
        {
            PR_lrKey,
            PR_udKey,
            PR_keys,
            Float:PR_position[3]
        };
```
And have packet ID 212

**Comment by ADRFranklin** [comment]
I will add support for this, I still need to know if the plugin is working as expected for you. At least than I am okay to move forward.

This shouldn't be too hard to implement, looking at the struct itself, it's simple. I've just had a thought. There might be an issue with Freezing data, since it doesn't freeze one one packet, it freezes them all. I will add a fix for that now, which means deprecating the old freeze native in favor of the new one that allows types to be used.

**Comment by NexiusTailer** [comment]
Well, currently there are the following things:
1. Make similar native also for FreezeSyncData as well as SendLastSyncData
2. Fix a little typo mistake in SKY.inc at this line "If a**n** type is specified it will sync that packet only"  :)

**Comment by ADRFranklin** [comment]
Thanks, I have fixed those issues. I have also added the Spectate sync for both Freeze and LastSend. 

Could you test these to make sure everything is okay :)
[release-windows.zip](https://github.com/oscar-broman/SKY/files/3996003/release-windows.zip)
[release-linux.tar.gz](https://github.com/oscar-broman/SKY/files/3996004/release-linux.tar.gz)

It's annoying Github won't met me upload .inc files, so had to zip it :(
[SKY.inc.zip](https://github.com/oscar-broman/SKY/files/3996007/SKY.inc.zip)

**Comment by NexiusTailer** [comment]
Seems like it's the old plugin version
```
[22:46:18] [debug] Run time error 19: "File or function is not found"
[22:46:18] [debug]  FreezeSyncPacket
[22:46:18] [debug] Run time error 19: "File or function is not found"
[22:46:18] [debug]  FreezeSyncPacket
[22:46:18] Script[gamemodes/nex-test.amx]: Run time error 19: "File or function is not found"
```

**Comment by ADRFranklin** [comment]
Errm, this is working for me just fine? Are you sure you have updated the plugin?

**Comment by NexiusTailer** [comment]
Sorry, it was my mistake because of mess up with YSF/SKY typed in the server.cfg, so that's loads fine. But despite this there are some problems with FreezeSyncPacket: if I freeze the player and apply for him
```
FreezeSyncPacket(playerid, E_PLAYER_SYNC, true);
```
or such way
```
FreezeSyncPacket(playerid, _, true);
```
The frozen player who is onfoot at the moment keeps moving around but without any animations (it fells like this player just slides on the ground)

**Comment by ADRFranklin** [comment]
I'm not entirely sure what causes that issue 😕

**Comment by ADRFranklin** [comment]
wait, so the issue is when frozen animations are not applied, is that the only issue?

**Comment by ADRFranklin** [comment]
[release-windows.zip](https://github.com/oscar-broman/SKY/files/3996259/release-windows.zip)
[release-linux.tar.gz](https://github.com/oscar-broman/SKY/files/3996260/release-linux.tar.gz)

@NexiusTailer Tell me if this fixes the animation syncing issue

**Comment by NexiusTailer** [comment]
> wait, so the issue is when frozen, animations are not applied, is that the only issue?

Made some video to show how it looks like (sorry for 640x480, it is just for the fastest rendering):
https://imgur.com/qsJhccd

> [release-windows.zip](https://github.com/oscar-broman/SKY/files/3996259/release-windows.zip)
> [release-linux.tar.gz](https://github.com/oscar-broman/SKY/files/3996260/release-linux.tar.gz)
> 
> @NexiusTailer Tell me if this fixes the animation syncing issue

As for it, I'll retest it now and check if the problem was fixed.

**Comment by NexiusTailer** [comment]
Hm, the problem still occurs, unfortunately...

**Comment by ADRFranklin** [comment]
Does the issue occur when using the old native?

**Comment by NexiusTailer** [comment]
So strange, but yes, it occurs also with FreezeSyncData and at the same time the problem remains on the previous SKY versions from the release section (v2.1.1). As far as I remember I tested it about 3-5 months ago and it worked well, despite the fact the player didn't be resynced when he changed his sync type (get veh or something like that).

**Comment by ADRFranklin** [comment]
[release-linux.tar.gz](https://github.com/oscar-broman/SKY/files/3996432/release-linux.tar.gz)
[release-windows.zip](https://github.com/oscar-broman/SKY/files/3996433/release-windows.zip)

I might have found the issue, hopefully 🤞

**Comment by ADRFranklin** [comment]
@NexiusTailer any luck yet?

**Comment by NexiusTailer** [comment]
The problem still remains for now

**Comment by ADRFranklin** [comment]
I don't know what is causing it, I checked both the PacketList and Pawn.Raknet to see if I have missed anything, and I haven't it all adds up. :(

**Comment by NexiusTailer** [comment]
I’ll try to check the old releases of the plugin to find out how long and with what version the problems started. Perhaps this will reduce the problem search area.

**Comment by ADRFranklin** [comment]
Yeah, that would be helpful thanks.

**Comment by NexiusTailer** [comment]
So finally I found from which version the problem starts: v2.0.0. When I tested it on 1.1.0, there was no problem with the function, but it just stopped working from the next update.

**Comment by ADRFranklin** [comment]
[release-linux.tar.gz](https://github.com/oscar-broman/SKY/files/4003726/release-linux.tar.gz)
[release-windows.zip](https://github.com/oscar-broman/SKY/files/4003727/release-windows.zip)

There is literally minimal difference between the 1.1 release and any releases after that with FrozenSync, so the only change that was made was the positioning of a certain check that was moved above.

If this fails, than I am really unsure as to what has caused it.

**Comment by NexiusTailer** [comment]
No, this doesn't help. While I was thinking about it I tested it both on 0.3.7-R2-1-1 server version and [0.3.7-R3](https://forum.sa-mp.com/showpost.php?p=4094602&postcount=55), but the result as in previous cases...

**Comment by ADRFranklin** [comment]
I'm not sure that helps us solve this :( Have you tried 0.3.DL? is it possible it's an issue with the 0.3.7 structs? or is the same issue appearing there too?

**Comment by ADRFranklin** [comment]
[release-linux.tar.gz](https://github.com/oscar-broman/SKY/files/4006630/release-linux.tar.gz)
[release-windows.zip](https://github.com/oscar-broman/SKY/files/4006631/release-windows.zip)

Okay I think I found the issue, thanks to Y_Less pointing a very important mistake. So hopefully this is all done now.

**Comment by NexiusTailer** [comment]
Yeah, that's finally okay. Thank you!

**Comment by NexiusTailer** [comment]
And I have another idea: maybe it would be wise to add to this enum:
```
enum E_SYNC_TYPES
{
    E_PLAYER_SYNC = 0,
    E_AIM_SYNC,
    E_VEHICLE_SYNC,
    E_PASSENGER_SYNC,
    E_SPECTATING_SYNC
};
```
Another, the last type `E_ANY_SYNC` or something like this to be able to freeze the player sync from exactly that packet which he sent before this function applied (so that the player couldn't change his sync type while his sync frozen and, for example, being "frozen-synced" onfoot and getting info a car after it will not affect other player seeing him in the vehicle as he would be still onfoot for them).

**Comment by ADRFranklin** [comment]
[release-windows.zip](https://github.com/oscar-broman/SKY/files/4007351/release-windows.zip)
[release-linux.tar.gz](https://github.com/oscar-broman/SKY/files/4007352/release-linux.tar.gz)
[SKY.inc.zip](https://github.com/oscar-broman/SKY/files/4007353/SKY.inc.zip)

Okay, I have added the ability to use `E_ANY_SYNC` which will freeze/re-send the last sync that came through.

**Comment by ADRFranklin** [comment]
Can you test it to make sure everything is good and report back? If all is good I will make a new release for it.

**Comment by NexiusTailer** [comment]
So after the test I found that the previous problem started to occur again: player moves around even his sync is frozen using E_ANY_SYNC.

**Comment by ADRFranklin** [comment]
@NexiusTailer Can you try the latest release?

**Comment by NexiusTailer** [comment]
> [release-windows.zip](https://github.com/oscar-broman/SKY/files/4007351/release-windows.zip)
> [release-linux.tar.gz](https://github.com/oscar-broman/SKY/files/4007352/release-linux.tar.gz)
> [SKY.inc.zip](https://github.com/oscar-broman/SKY/files/4007353/SKY.inc.zip)
> 
> Okay, I have added the ability to use `E_ANY_SYNC` which will freeze/re-send the last sync that came through.

I have tried this release.

**Comment by ADRFranklin** [comment]
Oh, errm. Okay. How is that possible?
Does it only happen with `E_ANY_SYNC ` ?

**Comment by ADRFranklin** [comment]
@NexiusTailer LOL, I forgot to tell you I changed `E_ANY_SYNC` to `E_LAST_SYNC` :D

**Comment by NexiusTailer** [comment]
> Oh, errm. Okay. How is that possible?
> Does it only happen with `E_ANY_SYNC ` ?

Yeah, the problem occurs for `E_ANY_SYNC` only and there were no such cases for `E_PLAYER_SYNC` as I tested it just now.

> @NexiusTailer LOL, I forgot to tell you I changed `E_ANY_SYNC` to `E_LAST_SYNC` :D

But I still have `E_ANY_SYNC` in SKY.inc in this enum, so I suppose this enum element should be passed to the plugin as a regular int number, isn't it?

**Comment by ADRFranklin** [comment]
@NexiusTailer How are you using it? Like are you still toggling it?

**Comment by NexiusTailer** [comment]
Just this way for freezing:
```
FreezeSyncPacket(playerid, E_ANY_SYNC, true);
```
and this for unfreezing:
```
FreezeSyncPacket(playerid, E_ANY_SYNC, false);
```

**Comment by ADRFranklin** [comment]
[release-windows.zip](https://github.com/oscar-broman/SKY/files/4007531/release-windows.zip)
[release-linux.tar.gz](https://github.com/oscar-broman/SKY/files/4007532/release-linux.tar.gz)

does this make any difference? I'm wondering if the conversation was not correct.

**Comment by NexiusTailer** [comment]
> [release-windows.zip](https://github.com/oscar-broman/SKY/files/4007531/release-windows.zip)
> [release-linux.tar.gz](https://github.com/oscar-broman/SKY/files/4007532/release-linux.tar.gz)
> 
> does this make any difference? I'm wondering if the conversation was not correct.

The problem still remains :(

**Comment by NexiusTailer** [comment]
So I've noticed you released a new version v2.2.1 and I just tested it. There is no such problem like with previous posted .DLLs here any more (the player stay on the same place for other when he sync frozen even with E_LAST_SYNC mode), but this type (E_LAST_SYNC) now works like any other type, e. g. when I do `FreezeSyncPacket(playerid, E_LAST_SYNC, true);` on an player who is onfoot all is ok, but then he enters the vehicle and any driver sync become visible for other again like if I did `E_PLAYER_SYNC`.

**Comment by ADRFranklin** [comment]
I don't really understand what you meant? You said it freezes them correctly, but then you said it doesn't freeze them when they enter a vehicle, but if you freeze a player, you must unfreeze them for them to enter a vehicle, so that doesn't make sense as to what the problem is?

**Comment by NexiusTailer** [comment]
> > [release-windows.zip](https://github.com/oscar-broman/SKY/files/4007531/release-windows.zip)
> > [release-linux.tar.gz](https://github.com/oscar-broman/SKY/files/4007532/release-linux.tar.gz)
> > does this make any difference? I'm wondering if the conversation was not correct.
> 
> The problem still remains :(

The first message was about testing this files (.dll):
> [release-windows.zip](https://github.com/oscar-broman/SKY/files/4007531/release-windows.zip)
> [release-linux.tar.gz](https://github.com/oscar-broman/SKY/files/4007532/release-linux.tar.gz)
> 
> does this make any difference? I'm wondering if the conversation was not correct.

and .inc file from here (as it was the latest .inc file shared):
> [release-windows.zip](https://github.com/oscar-broman/SKY/files/4007351/release-windows.zip)
> [release-linux.tar.gz](https://github.com/oscar-broman/SKY/files/4007352/release-linux.tar.gz)
> [SKY.inc.zip](https://github.com/oscar-broman/SKY/files/4007353/SKY.inc.zip)
> 
> Okay, I have added the ability to use `E_ANY_SYNC` which will freeze/re-send the last sync that came through.

And in that case when I test it, `E_ANY_SYNC` (last shared SKY.inc have exactly this type name in enum) wasn't work at all as the frozen-synced player has an ability to move for others like he move for himself.


The second message was about this files (.dll):
https://github.com/oscar-broman/SKY/releases/tag/2.2.1

and .inc file from here (as in the releases section there is no its own .inc file for every version):
https://github.com/oscar-broman/SKY/blob/1bd6e7bc7777f3b551177d8bcb79b7cadeadd071/SKY.inc

And in this case when I test it, now `E_LAST_SYNC` freezes single type of the synchronization (applied for a player who is onfoot => it will freeze only onfoot data and any other type of sync will be synced instead of onfoot and moreover will be synced without any freeze).


As for "if you freeze a player, you must unfreeze them for them to enter a vehicle" - I'm using FreezePlayerPacket without applying TogglePlayerControllable for the player (if you mean it) to test only the `FreezePlayerPacket` without any side effects to see if it works and whether it works correctly. I want to make anti-unfreeze that will freeze exactly the type of synchronization for a player that he sent before applying this function. And even if the player ignores the function of the “visual” freeze by the server (TogglePlayerControllable), his synchronization for others will continue to appear as if it had stopped moving, including ignoring any change in the type of synchronization (the player got into his car and started to drive off, but for others he should still stay onfoot in the last place he stood before this function was applied).

**Comment by ADRFranklin** [comment]
```
And in this case when I test it, now E_LAST_SYNC freezes single type of the synchronization (applied for a player who is onfoot => it will freeze only onfoot data and any other type of sync will be synced instead of onfoot and moreover will be synced without any freeze).
```

This is how I purposely coded it, this is what you explained to me you wanted, so this is what I gave you?

**Comment by NexiusTailer** [comment]
> This is how I purposely coded it, this is what you explained to me you wanted, so this is what I gave you?

Then, it seems, I didn't express myself very clearly, sorry about it :)
I just thought that it would be possible to block all types of synchronization at once with one option.

> Why are we talking about `TogglePlayerControllable`? Of course you would need to untoggle a frozen sync to have them enter a vehicle. (for other players) `E_LAST_SYNC` is exactly what it's name describes, it freezes the very last sync that was used, previous to when the native is called.

Just made sure any other functions like real freezing have nothing to do with it. So as for `E_LAST_SYNC` I thought it's an option not for freezing only one type of sync the player holds now.

**Comment by ADRFranklin** [comment]
So you want a way to freeze all current/future syncs for a player?

**Comment by NexiusTailer** [comment]
Yeah, now I (finally lol) understood that I gave one suggestion and got nice but different feature. And yeah, it would be very nice if you implement something like that I mentioned.

Btw, `E_LAST_SYNC` is still useful as it can be an easy solution for weapon-config which used an old FreezeSyncData without getting the player state. Now it can be update for a new native without any problem.

**Comment by NexiusTailer** [comment]
> So you want a way to freeze all current/future syncs for a player?

Sorry for the possible annoyance, but could you share some information when this addition will be available for testing? :)

**Comment by ADRFranklin** [comment]
Hi, sorry I have been a little busy with other projects, I will find time over the next few days to finally sort this.

**Comment by ADRFranklin** [comment]
[release-windows.zip](https://github.com/oscar-broman/SKY/files/4080554/release-windows.zip)
[release-linux.tar.gz](https://github.com/oscar-broman/SKY/files/4080555/release-linux.tar.gz)
[SKY.inc.zip](https://github.com/oscar-broman/SKY/files/4080557/SKY.inc.zip)

Try this, got a few minutes didn't take long.

**Comment by NexiusTailer** [comment]
Thanks, seems to work for me on windows server.
