### ISSUE TITLE
Failed (/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found

### ISSUE THREAD

**Issue by izrie1** [oscar-broman/SKY#34]
> [03:30:44]  Loading plugin: SKY.so
> [03:30:44]   Failed (/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by plugins/SKY.so))
> 
I need help on this. Currently using CentOS 7. If you are asking me to use other distros, I can't use other distros (due to this issue: https://forum.sa-mp.com/showthread.php?p=4022160)

**Comment by Jeroen52** [comment]
Can you use `yum whatprovides */libstdc++.so.6`?

**Comment by Jeroen52** [comment]
A simple Google search indicates that this could also be a possible solution.
https://stackoverflow.com/questions/44205687/glibcxx-3-4-21-not-found-on-centos-7

**Comment by izrie1** [comment]
> [izrie1@asauthrp ~]$ sudo yum whatprovides */libstdc++.so.6
> Loaded plugins: fastestmirror
> Loading mirror speeds from cached hostfile
>  * base: mirror.checkdomain.de
>  * epel: ftp.plusline.net
>  * extras: mirror.ratiokontakt.de
>  * remi-php72: mirror.23media.com
>  * remi-safe: mirror.23media.com
>  * updates: linux.darkpenguin.net
> libstdc++-4.8.5-39.el7.i686 : GNU Standard C++ Library
> Repo        : base
> Matched from:
> Filename    : /usr/lib/libstdc++.so.6
> 
> 
> 
> libstdc++-4.8.5-39.el7.x86_64 : GNU Standard C++ Library
> Repo        : base
> Matched from:
> Filename    : /usr/lib64/libstdc++.so.6
> 
> 
> 
> libstdc++-4.8.5-39.el7.i686 : GNU Standard C++ Library
> Repo        : @base
> Matched from:
> Filename    : /usr/lib/libstdc++.so.6
> 
> 
> 
> libstdc++-4.8.5-39.el7.x86_64 : GNU Standard C++ Library
> Repo        : @base
> Matched from:
> Filename    : /usr/lib64/libstdc++.so.6

Here what it says. 

By the way concerning the possible solution you shared, I have tried it before. It ruined my VPS

**Comment by Jeroen52** [comment]
It might be just because it is early but I don't see why it'd ruin the VPS.

Either way, use the following.

`yum -y install libstdc++.i686`

**Comment by izrie1** [comment]
> 
[izrie1@arp ~]$ sudo yum -y install libstdc++.i686
[sudo] password for izrie1:
Loaded plugins: fastestmirror

Loading mirror speeds from cached hostfile
epel/x86_64/metalink                                     |  19 kB     00:00
 * base: mirror.checkdomain.de
 * epel: ftp.plusline.net
 * extras: mirror.ratiokontakt.de
 * remi-php72: mirror.23media.com
 * remi-safe: mirror.23media.com
 * updates: linux.darkpenguin.net
base                                                     | 3.6 kB     00:00
epel                                                     | 5.4 kB     00:00
extras                                                   | 2.9 kB     00:00
remi-php72                                               | 3.0 kB     00:00
remi-safe                                                | 3.0 kB     00:00
updates                                                  | 2.9 kB     00:00
(1/2): epel/x86_64/updateinfo                              | 1.0 MB   00:00
(2/2): epel/x86_64/primary_db                              | 6.9 MB   00:00
Package libstdc++-4.8.5-39.el7.i686 already installed and latest version
Nothing to do
[izrie1@asauthrp ~]$
[izrie1@asauthrp ~]$ sudo yum -y install libstdc++.i686
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.checkdomain.de
 * epel: ftp.plusline.net
 * extras: mirror.ratiokontakt.de
 * remi-php72: mirror.23media.com
 * remi-safe: mirror.23media.com
 * updates: mirror.checkdomain.de
Package libstdc++-4.8.5-39.el7.i686 already installed and latest version
Nothing to do

It's already latest version

**Comment by OriginalNutter** [comment]
I was using CentOS once upon a time, because of the timeout issue, and eventually got SKY working by building it myself. During the process, the correct version of the library was installed.

In the end, I switched over to Debian 10 which was not suffering from the timeout issue.

**Comment by ADRFranklin** [comment]
I have said this many times, and will continue to say it. Centos might be a stable distro, but I is always so far behind current technologies. As someone who has used Debian/Ubuntu for almost 10 years, I can say I have no issues running software like sa-mp on them.

Debian/Ubuntu have later versions that do support newer standards, which a lot of plugins theses days take advantage of.

Could I ask which version of SKY are you using? Tbh, I should of statically build the last 3 versions, so your version of glibc, shouldn't really matter.

**Comment by izrie1** [comment]
> I have said this many times, and will continue to say it. Centos might be a stable distro, but it is always so far behind current technologies. As someone who has used Debian/Ubuntu for almost 10 years, I can say I have no issues running software like sa-mp on them.
> 
> Debian/Ubuntu have later versions that do support newer standards, which a lot of plugins theses days take advantage of.
> 
> Could I ask which version of SKY are you using? Tbh, I should of statically built the last 3 versions, so your version of glibc, shouldn't really matter.

I am using 2.0.0

**Comment by ADRFranklin** [comment]
I would advise you to upgrade OS to something more later, if you can. If you unable to, You will need to compile it on Centos, yourself.

**Comment by ADRFranklin** [comment]
Can't promise this will work, but you could try the instructions at the bottom of this page: 
https://altlinux.pkgs.org/sisyphus/classic-i586/libstdc++6-9.2.1-alt1.i586.rpm.html

**Comment by izrie1** [comment]
> I would advise you to upgrade OS to something more later, if you can. If you are unable to, you will need to compile it on Centos, yourself.
How do I compile the plugin on CentOS? I'm new on this matter, usually I obtain by downloading the pre-compiled plugins.

**Comment by izrie1** [comment]
> I would advise you to upgrade OS to something more later, if you can. If you are unable to, you will need to compile it on Centos, yourself.

How do I compile the plugin on CentOS? I'm new on this matter, usually I obtain by downloading the pre-compiled plugins.

**Comment by ADRFranklin** [comment]
You can find the build instructions on the Readme now.
