### ISSUE TITLE
Compile Error - Windows 10 - visual studio 16 2019 - Cmake 3.16.2

### ISSUE THREAD

**Issue by InterSstellar** [oscar-broman/SKY#38]
Hi, i have some issue with compiling.

i use visual studio community 16 2019 and Cmake 3.16.2.

While I'm Building Only thing that can not be found is alloca.h, but anyways it says Generating done.

But when i use "cmake --build . --config Release" i get a huge number of errors.

This is what Errors say, i put them in a .txt file
[Errors.txt](https://github.com/oscar-broman/SKY/files/4003653/Errors.txt)

Please Help Me I Really Need this.

If Anyone Can Upload A Pre-compiled DLL version of this plugin please do it for me :( :( :(

**Comment by ADRFranklin** [comment]
The plugin is statically built, why are you trying to build it? Use the release section.

**Comment by InterSstellar** [comment]
Oh My God!!!!
I did not know there is a Section called release!!!
Im New to Git Hub And Programing :D

you saved me a lot of time Thank You very Much <3 <3 <3

And Sorry For My Bad English :D
