### ISSUE TITLE
2.2.0 - Causes crash

### ISSUE THREAD

**Issue by elvianod982** [oscar-broman/SKY#39]
SKY 2.2.0 causes my gamemode to crash. 2.1.1 is fine.

It seems to happen when weapon shots are fired.

Is this a known issue?

**Comment by elvianod982** [comment]
Here is a crash log: https://pastebin.com/raw/gbcqk9kU

**Comment by ADRFranklin** [comment]
Ah, it seems I accidentally pushed more than I wanted too. Should be a simple fix.

**Comment by ADRFranklin** [comment]
@elvianod982 Please use 2.2.1 Release

**Comment by elvianod982** [comment]
That fixed it, thanks.
