### ISSUE TITLE
Players vanish when shot - SKY 2.2.1

### ISSUE THREAD

**Issue by elvianod982** [oscar-broman/SKY#40]
Since updating from SKY 2.1.1 to SKY 2.2.0 (or well, the crash fix version - 2.2.1) players on my server randomly disappear whilst being shot at. This has been confirmed with multiple players, even staff, so I'm confident that it's a SKY bug rather than a hacker. I'm also confident it was introduced with SKY 2.2.x as this has never happened with 2.1.x.

I have captured a recording to demonstrate this: https://streamable.com/ae9ac

**Comment by ADRFranklin** [comment]
I am unable to re-create this? Could you make a minimal reproducible example script that shows this problem?

**Comment by elvianod982** [comment]
Thanks for your prompt response.

Sadly, it isn't one of those things that is reproducible on the first try. It took a few minutes for me to re-create it on my own server. I can't really give any script examples since my server is very basic and weapon-config is at the core of it. I have no custom weapon-config/sky code; it's all stock. 

If you would be open to compiling a Linux release of 2.1.1 for me, but with the fix for "Fixed a bug, where freezing a players sync, would not work correctly, and you would see them sliding across the floor while dead", that would suit me, as the only reason I would like this update is for this fix.

**Comment by ADRFranklin** [comment]
[release-windows.zip](https://github.com/oscar-broman/SKY/files/4008649/release-windows.zip)
[release-linux.tar.gz](https://github.com/oscar-broman/SKY/files/4008650/release-linux.tar.gz)

Any chance you could try this for me, and see if it makes any difference?

**Comment by ADRFranklin** [comment]
I'm probably going to write my own libraries for a clean Raknet/CNetGame interface. Because both SKY/YSF use a old style and it's not very safe to use.

**Comment by ADRFranklin** [comment]
@elvianod982 Any news from this?

**Comment by elvianod982** [comment]
I just tried out the release-linux.tar.gz that you provided, but the results are the same unfortunately.

Recording: https://streamable.com/tjwdc

You will see I was dueling the player, and 5 seconds in, they disappeared.

**Comment by ADRFranklin** [comment]
I am unable to reproduce this issue? Any more information you can give me?
Can you confirm the version you are using?

**Comment by elvianod982** [comment]
It takes a few minutes of gameplay sometimes and there seems to be no rhyme nor reason as to what causes it. It doesn't happen with every single player all the time. 

I am using the release-linux.tar.gz version that you uploaded to this issue 16 hours ago. The server runs 0.3.7-R2, and CentOS 8.

Would you mind providing a Linux version of SKY 2.1.1 but with the patch for **Fixed a bug, where freezing a players sync, would not work correctly, and you would see them sliding across the floor while dead**? 

That is all I need really, as the plugin is otherwise perfect from my point of view.

**Comment by ADRFranklin** [comment]
The one I posted has that fix already, that is already in the last 2 releases too.

**Comment by elvianod982** [comment]
I apologize, it might be that I am not explaining properly.

The one you posted seems to be the 2.2.x release, which has the player vanishing problem highlighted in this issue. I can't use any version of SKY 2.2.x as it stands for that reason.

Per https://github.com/oscar-broman/SKY/releases, 2.2.0 is the version that has the "freezing a players sync" fix. Can you provide me with a Linux version of 2.1.1, but with that fix added to it (nothing else)?

**Comment by ADRFranklin** [comment]
I don't think the issue is to do with SKY in this case, I have been testing this for about 30 minutes now, on both a local and remote server. I have tried with 3 different people and have no had any luck reproducing this bug.

Until more evidence comes along which can prove the issue to be related to SKY, I can't really do anything about your issue.

**Comment by elvianod982** [comment]
Understood. 

Could you tell me exactly which commit addressed the "Fixed a bug, where freezing a players sync, would not work correctly, and you would see them sliding across the floor while dead" issue? I will compile 2.1.1 but with that particular fix. That's all I need and then I should be good to go.

**Comment by ADRFranklin** [comment]
https://github.com/oscar-broman/SKY/commit/a0606e5c01a317255764edde2a5e0856ca2f8c4d
that is the commit, that fixes the syncing bug

**Comment by ADRFranklin** [comment]
@elvianod982 

[release-linux.tar.gz](https://github.com/oscar-broman/SKY/files/4013181/release-linux.tar.gz)
[release-windows.zip](https://github.com/oscar-broman/SKY/files/4013182/release-windows.zip)

Can you confirm that this fixes the problem for you?
