### ISSUE TITLE
Hided player

### ISSUE THREAD

**Issue by bigheada** [oscar-broman/SKY#41]
Hi,
I have problem with last releases version. I uses weapon-config include and after I hit some player, then is this player hidden ( after the player used ESC, is again visible ). If i uses older version SKY ( about 1-2 years old version ) its works. 
- weapon-config.inc last version

Where the problem could be?

**Comment by ADRFranklin** [comment]
3 people have reported this issue to me, but none so far have given me enough information to really find the issue.

**Comment by ADRFranklin** [comment]
[release-linux.tar.gz](https://github.com/oscar-broman/SKY/files/4013010/release-linux.tar.gz)
[release-windows.zip](https://github.com/oscar-broman/SKY/files/4013011/release-windows.zip)

Would you be willing to try this for me? It's a small change in the way it's built

**Comment by bigheada** [comment]
ok, I will test

**Comment by bigheada** [comment]
same problem...i tried command for re-warping my position but i was still hided for other player, after i go to the windows and back i was visible. Meybe i will try debug where in the weapon config is problem and if I find anything, i will write ?

**Comment by ADRFranklin** [comment]
[release-linux.tar.gz](https://github.com/oscar-broman/SKY/files/4013059/release-linux.tar.gz)
[release-windows.zip](https://github.com/oscar-broman/SKY/files/4013060/release-windows.zip)

Okay this is all I can think of right now, if this works cool. But if it doesn't I'm going to need some time to fix it.

**Comment by bigheada** [comment]
now it works correct

**Comment by ADRFranklin** [comment]
Brilliant, so I found the issue. Thanks :)
