### ISSUE TITLE
[Suggestion] implement AttachPlayerObjectToOvject

### ISSUE THREAD

**Issue by realhus** [oscar-broman/SKY#44]
It might be a silly request but AttachPlayerObjectToObject is the reason that alot of server owners use YSF . And its essential for some functions in streamer plugin. I saw that SKY plugin share some YSF features... such as textdraw position. Why not to add this function too.. it would be really helpfull.. i dont want to use YSF in addition to SKY just for one additional function.. thanks

**Comment by ADRFranklin** [comment]
SKY was original designed to work specifically with `weapon-config` so the textdraw natives, where used for the custom healthbar. 

SKY is not supposed to be another YSF, and instead just offers more functionality to handle players syncing. You can use YSF/SKY together, so if you want to use that and SKY there should be no issues with it.
