### ISSUE TITLE
Multi Thread Plugin

### ISSUE THREAD

**Issue by InterSstellar** [oscar-broman/SKY#45]
Hi. Can You Release A Multi Thread Plugin With Good Natives And Callbacks. It Will Be Soooooo Handy.

Im Running a Cops and robbers server and every time a cop presses mouse3 i have to find the nearest player and cuff him. so i have to loop throw all players and check the distance between players an it takes a lot for server and if there are some players fighting each other they all will lag for at least 100 miliseconds and that's not GooD :(
but if i was able to loop throw players in another thread and receive the result from a callback there was no stress on server.

**Comment by ADRFranklin** [comment]
You can use plugins like PawnPlus for exactly this reason, this issue is not related to SKY in any way, and is not something that should be looked into.

PawnPlus: https://github.com/IllidanS4/PawnPlus

Please do not make issues about topics that do not relate to the repo at hand.

**Comment by InterSstellar** [comment]
I'm newbie and i don't know how to communicate with you because of that i post a issue :(((((
And Thank You Very Much for your good response <3
