### ISSUE TITLE
Knife kill / Dying in exploding vehicle

### ISSUE THREAD

**Issue by SaboT94** [oscar-broman/SKY#46]
Hello,

So i have few issues, i put weapon include and SKY , working on last updates on my server,
i have few questions/issues.

When someone kills with knife, OnPlayerDeath is not called, kill is not counting.

And for second, usually you sit in burning vehicle, vehicle explode, you get out of vehicle and dye, now with include and plugin, right after explode you get respawned, sometimes player get respawned 1-2 times and ending up in ganton like when you press F4, then i must kill him manually to respawn right, how can i manipulate with that? (That explosion bug is happening when you explode and setvehicletorespawn)

**Comment by ADRFranklin** [comment]
This isn't a SKY related issue. This is a weapon-config issue. I would instead report the issue there to be fixed.
