### ISSUE TITLE
Corpse collision

### ISSUE THREAD

**Issue by Diablosrouge** [oscar-broman/SKY#49]
Hello,

After a player dies, his corpse stays in the floor for a while, but it has collision and limits player movement. Is there any way to disable this collision?

Best Regards,
Diablosrouge

**Comment by ADRFranklin** [comment]
Unfortunately it's not possible to achieve this without client side modifications, which is something we will not be doing.

**Comment by Diablosrouge** [comment]
Thank you for the reply :)
