### ISSUE TITLE
Hi , why did you remove all releases ?

### ISSUE THREAD

**Issue by ghost** [oscar-broman/SKY#5]
please man , i need 0.3.7 version
if you don't want to share it here anymore please give me a download link
REALLY important because fall damage and etc. doesn't detect

**Comment by oscar-broman** [comment]
Compiling on Linux is as easy as `make`.  Not sure about Windows - I don't use it. @Whitetigerswt could you?

**Comment by amirab** [comment]
@oscar-broman you mean you don't have windows version in your system ?

**Comment by Whitetigerswt** [comment]
I'll compile one today

**Comment by Whitetigerswt** [comment]
Make that tomorrow, I had to spend time installing visual studio today, and it took longer than I thought

**Comment by oscar-broman** [comment]
You could try doing it yourself, @amirab, by opening the solution file in Visual Studio and clicking *Build*.

**Comment by amirab** [comment]
@oscar-broman i can't because i have Visual Studio 2012 , i can't install 2013 i donno why 
if you can make it usable for 2012 you will have my BIG Thanks :+1: 
but i need 0.3.7 anyway because damage system is now terrible
	
!!

**Comment by oscar-broman** [comment]
Alright. Let's hope the albino tiger sorts it out today.

**Comment by Whitetigerswt** [comment]
http://1drv.ms/1SxwkEN

**Comment by amirab** [comment]
i get these : 

SA-MP Dedicated Server
----------------------
v0.3.7, (C)2005-2015 SA-MP Team

[14:43:46] 
[14:43:46] Server Plugins
[14:43:46] --------------
[14:43:46]  Loading plugin: skywt.dll
[14:43:46] Error: Unknown Windows server version


and this is a picture of some Native Backtrace :

http://upir.ir/khordad94/guest/issues.png

**Comment by oscar-broman** [comment]
Could you compile in debug mode?

**Comment by amirab** [comment]
@oscar-broman actually somebody did before me 
here is the output : 

[16:25:59]  Loading plugin: SKY
[16:25:59] [debug] Server crashed due to an unknown error
[16:26:01] [debug] Native backtrace:
[16:26:01] [debug] #0 54ce2dfc in UnwindUpVec () from plugins\SKY.DLL
[16:26:01] [debug] #1 54ccd1b0 in subhook_new () from plugins\SKY.DLL
[16:26:01] [debug] #2 54ccfba2 in InstallPreHooks () from plugins\SKY.DLL
[16:26:01] [debug] #3 54cd1cdf in Load () from plugins\SKY.DLL
[16:26:01] [debug] #4 0046a4db in ?? () from samp-server.exe

**Comment by oscar-broman** [comment]
Any idea why subhook is crashing @Zeex?

**Comment by Zeex** [comment]
@amirab Can you show the stack trace from Visual Studio (by running the server under VS debugger)?

**Comment by Zeex** [comment]
Actually, nevermind @amirab, I've found the location:

https://github.com/oscar-broman/SKY/blob/master/lib/subhook/subhook_x86.c#L234

So it seems that `CAddress::FUNC_GetPacketID` passed to `subhook_new` in `InstallPreHooks` as `src` was pointing to non-writable memory, most likely being `NULL` looking at its usages. I guess it couldn't find the pattern?

**Comment by Yiin-** [comment]
It only happens if another plugin subhook that function (e.g. YSF).

**Comment by oscar-broman** [comment]
Oh. Does it work on Linux with YSF and SKY?

**Comment by amirab** [comment]
@oscar-broman @Whitetigerswt 
this is my plugin list : 
sky1.dll streamer.dll sscanf.dll  mysql.dll MapAndreas.dll

you think which of them subhook that function ? ?

**Comment by oscar-broman** [comment]
None of them hooks that function.

Are you sure you don't have a RC test version?

**Comment by amirab** [comment]
i'm using samp 0.3.7 r1 not RC
and using @Whitetigerswt 's compiled SKY version

this is top of server log : 

SA-MP Dedicated Server
----------------------
v0.3.7, (C)2005-2015 SA-MP Team

[22:32:20] 
[22:32:20] Server Plugins
[22:32:20] --------------
[22:32:20]  Loading plugin: sky.dll
[22:32:20] Error: Unknown Windows server version

i mean it says Unknown Windows server version

why ? i don't know and crashing process will start exactly at loading gamemode

**Comment by amirab** [comment]
@oscar-broman So dude , what happened my server's using this
