### ISSUE TITLE
SetPlayerTeamForPlayer

### ISSUE THREAD

**Issue by RodrigoMSR** [oscar-broman/SKY#50]
It would be really nice to have this function in the plugin, it would be useful for a damage system I have, the function would just send an RPC.

```
SetPlayerTeam - RPC ID: 69
Parameters: UINT16 wPlayerID, UINT8 bTeamID
```

It would help me a lot, sorry if this seems useless...

**Comment by ADRFranklin** [comment]
errm What? I don't understand what the point of this is?

**Comment by RodrigoMSR** [comment]
In a server-side damage system, players can typically destroy allied vehicles with grenade, bazooka, heavy vehicles and drive-by.

To solve this, I put all players on the same team and disable vehicle damage between allies. When a player enters a vehicle, he will see all others that are not on the same team as enemies (NO_TEAM), making it possible for him to take damage normally from them.

```
OnPlayerStateChange
  playerLoop(i)
    if(IsPlayerStreamedIn...)
      if(team[i] != team[driver])
        SetPlayerTeamForPlayer(i, NO_TEAM, driver); //"driver" see "i" as enemy
```

I managed to create the function from similar ones in the plugin just now, please disregard this issue.
