### ISSUE TITLE
OnPlayerUpdate stops being called

### ISSUE THREAD

**Issue by punkochel** [oscar-broman/SKY#53]
At calling ShowPlayerDialog, stops working OnPlayerUpdate, but when closed window dialog everything works as it should.

**Comment by ADRFranklin** [comment]
What makes you think that is related to SKY exactly? We don't really do anything with dialogs. So this is probably more related to weapon-config then SKY

**Comment by punkochel** [comment]
And indeed, now started checking and it turned out that the problem is fixes.inc. I dont's know why I decided what it is SKY. Sorry.

And Indeed, now I started checking and it turned out that the problem is in fixes.inc. I don’t know why I decided earlier that it was SKY. Sorry.
