### ISSUE TITLE
Am i the only one who don't know this?

### ISSUE THREAD

**Issue by Xeonmeister** [oscar-broman/SKY#7]
My question is: How to use this? I downloaded "weapon-config" which requires this plugin. So i downloaded the plugin and I only see a couple of files without any instruction that tells me what to do. I'm so confused. I tryed to find something to make it work, but noone has written about it yet. I know that it's so stupid, but I don't know how to make it work.

**Comment by oscar-broman** [comment]
Are you on Linux or Windows?

**Comment by Xeonmeister** [comment]
Windows
